services:
  app:
    image: fibbicles/nextcloud:fpm
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=nextcloud_pass
      - NEXTCLOUD_ADMIN_USER=admin  # Admin username for Nextcloud setup
      - NEXTCLOUD_ADMIN_PASSWORD=admin_pass  # Admin password for Nextcloud setup
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    depends_on:
      - db  # Ensure Nextcloud starts after MariaDB

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass  # Root password for MariaDB
      - MYSQL_DATABASE=nextcloud  # Name of the Nextcloud database
      - MYSQL_USER=nextcloud_user  # MariaDB user for Nextcloud
      - MYSQL_PASSWORD=nextcloud_pass  # Password for the Nextcloud user
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - '3306'

  onlyoffice-document-server:
    image: fibbicles/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    image: fibbicles/nginx:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
