services:
  app:
    image: fibbicles/nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html

  onlyoffice-document-server:
    image: fibbicles/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    image: fibbicles/nginx:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
